"""
ResearchMind AI - CLI Pipeline
Supports: revision loop, fact-checking, multi-topic comparison, export formats.
"""
import os
import sys
import json
import time
from datetime import datetime
from dotenv import load_dotenv

# Add project root to path so imports work from any entry point
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

load_dotenv()

from agents.agents import (
    build_search_agent,
    build_reader_agent,
    build_writer_chain,
    build_revision_chain,
    build_critic_chain,
    build_fact_checker_chain,
    build_comparison_chain,
    parse_critic_score,
    AVAILABLE_MODELS,
)


def validate_api_keys(model_name: str = "mistral-small-latest"):
    """Validate that required API keys are set for the chosen model."""
    provider = AVAILABLE_MODELS.get(model_name, "Mistral")
    key_map = {
        "Mistral": "MISTRAL_API_KEY",
        "OpenAI": "OPENAI_API_KEY",
        "Google": "GOOGLE_API_KEY",
    }
    required_key = key_map.get(provider, "MISTRAL_API_KEY")
    if not os.getenv(required_key):
        raise EnvironmentError(f"Missing {required_key} in .env file for {provider} models.")

    if not os.getenv("TAVILY_API_KEY"):
        raise EnvironmentError("Missing TAVILY_API_KEY in .env file (required for web search).")


def export_report_markdown(report: str, filename: str = "research_report.md"):
    with open(filename, "w", encoding="utf-8") as f:
        f.write(report)
    return filename


def export_report_html(report: str, topic: str, filename: str = "research_report.html"):
    import markdown
    html_body = markdown.markdown(report)
    html = f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>{topic} - Research Report</title>
<style>body{{font-family:Georgia,serif;max-width:800px;margin:2rem auto;padding:0 1rem;line-height:1.8;color:#222;}}
h1,h2,h3{{color:#1a1a2e;}}a{{color:#4f8ef7;}}</style></head>
<body><h1>{topic}</h1>{html_body}
<hr><p><em>Generated by ResearchMind AI on {datetime.now().strftime('%Y-%m-%d %H:%M')}</em></p>
</body></html>"""
    with open(filename, "w", encoding="utf-8") as f:
        f.write(html)
    return filename


def export_report_pdf(report: str, topic: str, filename: str = "research_report.pdf"):
    from fpdf import FPDF

    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 10, topic, new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    pdf.ln(5)
    for line in report.split("\n"):
        if line.startswith("## "):
            pdf.set_font("Helvetica", "B", 13)
            pdf.cell(0, 8, line.replace("## ", ""), new_x="LMARGIN", new_y="NEXT")
            pdf.set_font("Helvetica", "", 10)
        elif line.startswith("# "):
            pdf.set_font("Helvetica", "B", 15)
            pdf.cell(0, 10, line.replace("# ", ""), new_x="LMARGIN", new_y="NEXT")
            pdf.set_font("Helvetica", "", 10)
        elif line.strip():
            pdf.multi_cell(0, 6, line)
        else:
            pdf.ln(3)
    pdf.output(filename)
    return filename


def export_report_docx(report: str, topic: str, filename: str = "research_report.docx"):
    from docx import Document

    doc = Document()
    doc.add_heading(topic, level=0)
    for line in report.split("\n"):
        if line.startswith("## "):
            doc.add_heading(line.replace("## ", ""), level=2)
        elif line.startswith("# "):
            doc.add_heading(line.replace("# ", ""), level=1)
        elif line.startswith("- "):
            doc.add_paragraph(line[2:], style="List Bullet")
        elif line.strip():
            doc.add_paragraph(line)
    doc.save(filename)
    return filename


def run_research_pipeline(
    topic: str,
    model_name: str = "mistral-small-latest",
    max_revisions: int = 2,
    score_threshold: int = 8,
    depth: str = "Standard",
) -> dict:
    """Run the full research pipeline with revision loop and fact-checking."""

    validate_api_keys(model_name)

    max_search = {"Quick": 3, "Standard": 5, "Deep": 10}.get(depth, 5)
    state = {"revisions": [], "timings": {}}
    start_time = time.time()

    # ── Step 1: Search ────────────────────────────────────────────────────────
    print("🔍 Step 1: Searching the web...")
    t0 = time.time()
    search_agent = build_search_agent(model_name)
    search_result = search_agent.invoke({
        "messages": [{"role": "user", "content": f"Gather comprehensive research on: {topic}. Find at least {max_search} diverse sources."}]
    })
    state["search_results"] = search_result["messages"][-1].content
    state["timings"]["search"] = round(time.time() - t0, 1)
    print(f"   ✅ Done ({state['timings']['search']}s)")

    # ── Step 2: Reader ────────────────────────────────────────────────────────
    print("📖 Step 2: Reading and extracting findings...")
    t0 = time.time()
    reader_agent = build_reader_agent(model_name)
    reader_result = reader_agent.invoke({
        "messages": [{
            "role": "user",
            "content": f"""Synthesize the research below into a structured report.

**Topic:** {topic}

**Research Data:**
{state['search_results']}

Structure:
## 1. Executive Summary
## 2. Introduction
## 3. Key Findings
## 4. Analysis & Insights
## 5. Conclusion
## 6. Sources

Guidelines: objective, factual, professional, minimum 500 words."""
        }]
    })
    state["reader_output"] = reader_result["messages"][-1].content
    state["timings"]["reader"] = round(time.time() - t0, 1)
    print(f"   ✅ Done ({state['timings']['reader']}s)")

    # ── Step 3: Writer ────────────────────────────────────────────────────────
    print("✍️  Step 3: Writing research report...")
    t0 = time.time()
    writer = build_writer_chain(model_name)
    report = writer.invoke({"topic": topic, "research": state["reader_output"]})
    state["research_report"] = report
    state["timings"]["writer"] = round(time.time() - t0, 1)
    print(f"   ✅ Done ({state['timings']['writer']}s)")

    # ── Step 4: Critic + Revision Loop ────────────────────────────────────────
    critic = build_critic_chain(model_name)
    revision_chain = build_revision_chain(model_name)

    for revision_num in range(max_revisions):
        print(f"🎯 Step 4.{revision_num + 1}: Critic reviewing (revision {revision_num + 1}/{max_revisions})...")
        t0 = time.time()
        feedback = critic.invoke({"topic": topic, "report": state["research_report"]})
        score = parse_critic_score(feedback)
        elapsed = round(time.time() - t0, 1)

        revision_entry = {
            "revision": revision_num + 1,
            "score": score,
            "feedback": feedback,
            "time": elapsed,
        }
        state["revisions"].append(revision_entry)
        state["critic_feedback"] = feedback
        state["critic_score"] = score
        print(f"   Score: {score}/10 ({elapsed}s)")

        if score >= score_threshold:
            print(f"   ✅ Score {score}/10 meets threshold ({score_threshold}). Done!")
            break

        if revision_num < max_revisions - 1:
            print(f"   ↻ Revising report based on feedback...")
            t0 = time.time()
            revised = revision_chain.invoke({
                "topic": topic,
                "report": state["research_report"],
                "feedback": feedback,
            })
            state["research_report"] = revised
            print(f"   ✅ Revision done ({round(time.time() - t0, 1)}s)")

    # ── Step 5: Fact-Checker ──────────────────────────────────────────────────
    print("🔎 Step 5: Fact-checking report...")
    t0 = time.time()
    fact_checker = build_fact_checker_chain(model_name)
    fact_check = fact_checker.invoke({
        "topic": topic,
        "report": state["research_report"],
        "raw_research": state["search_results"],
    })
    state["fact_check"] = fact_check
    state["timings"]["fact_check"] = round(time.time() - t0, 1)
    print(f"   ✅ Done ({state['timings']['fact_check']}s)")

    state["timings"]["total"] = round(time.time() - start_time, 1)
    print(f"\n🏁 Pipeline complete in {state['timings']['total']}s")
    return state


def run_comparison_pipeline(
    topics: list[str],
    model_name: str = "mistral-small-latest",
    depth: str = "Standard",
) -> dict:
    """Run research on multiple topics and produce a comparative analysis."""

    validate_api_keys(model_name)

    max_search = {"Quick": 3, "Standard": 5, "Deep": 10}.get(depth, 5)
    state = {"per_topic": {}, "timings": {}}
    start_time = time.time()

    # Research each topic
    for i, topic in enumerate(topics):
        print(f"🔍 Researching topic {i + 1}/{len(topics)}: {topic}")
        search_agent = build_search_agent(model_name)
        search_result = search_agent.invoke({
            "messages": [{"role": "user", "content": f"Research: {topic}. Find {max_search} sources."}]
        })
        state["per_topic"][topic] = search_result["messages"][-1].content

    # Build comparison
    print("📊 Writing comparative analysis...")
    combined_research = "\n\n".join(
        f"=== {t} ===\n{data}" for t, data in state["per_topic"].items()
    )
    comparison = build_comparison_chain(model_name)
    state["comparison_report"] = comparison.invoke({
        "topics": ", ".join(topics),
        "research": combined_research,
    })

    # Critique comparison
    print("🎯 Critiquing comparison...")
    critic = build_critic_chain(model_name)
    state["critic_feedback"] = critic.invoke({
        "topic": f"Comparison: {', '.join(topics)}",
        "report": state["comparison_report"],
    })
    state["critic_score"] = parse_critic_score(state["critic_feedback"])

    state["timings"]["total"] = round(time.time() - start_time, 1)
    print(f"🏁 Comparison complete in {state['timings']['total']}s")
    return state


# ── Research History ──────────────────────────────────────────────────────────
HISTORY_FILE = os.path.join(os.path.dirname(__file__), "..", "research_history.json")


def save_to_history(topic: str, state: dict):
    history = load_history()
    entry = {
        "topic": topic,
        "timestamp": datetime.now().isoformat(),
        "report": state.get("research_report", state.get("comparison_report", "")),
        "critic_feedback": state.get("critic_feedback", ""),
        "critic_score": state.get("critic_score", 0),
        "fact_check": state.get("fact_check", ""),
    }
    history.append(entry)
    with open(HISTORY_FILE, "w", encoding="utf-8") as f:
        json.dump(history, f, indent=2, ensure_ascii=False)


def load_history() -> list:
    if os.path.exists(HISTORY_FILE):
        with open(HISTORY_FILE, "r", encoding="utf-8") as f:
            return json.load(f)
    return []


if __name__ == "__main__":
    topic = input("Enter a research topic: ")
    result = run_research_pipeline(topic)
    print("\n" + "=" * 60)
    print("FINAL REPORT")
    print("=" * 60)
    print(result["research_report"])
    print("\n" + "=" * 60)
    print("CRITIC FEEDBACK")
    print("=" * 60)
    print(result["critic_feedback"])
    print("\n" + "=" * 60)
    print("FACT CHECK")
    print("=" * 60)
    print(result["fact_check"])
